// Generated by gencpp from file visual_servoing/CameraObject.msg
// DO NOT EDIT!


#ifndef VISUAL_SERVOING_MESSAGE_CAMERAOBJECT_H
#define VISUAL_SERVOING_MESSAGE_CAMERAOBJECT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>
#include <geometry_msgs/Vector3.h>

namespace visual_servoing
{
template <class ContainerAllocator>
struct CameraObject_
{
  typedef CameraObject_<ContainerAllocator> Type;

  CameraObject_()
    : label()
    , center()
    , size()  {
    }
  CameraObject_(const ContainerAllocator& _alloc)
    : label(_alloc)
    , center(_alloc)
    , size(_alloc)  {
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _label_type;
  _label_type label;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _center_type;
  _center_type center;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _size_type;
  _size_type size;




  typedef boost::shared_ptr< ::visual_servoing::CameraObject_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::visual_servoing::CameraObject_<ContainerAllocator> const> ConstPtr;

}; // struct CameraObject_

typedef ::visual_servoing::CameraObject_<std::allocator<void> > CameraObject;

typedef boost::shared_ptr< ::visual_servoing::CameraObject > CameraObjectPtr;
typedef boost::shared_ptr< ::visual_servoing::CameraObject const> CameraObjectConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::visual_servoing::CameraObject_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::visual_servoing::CameraObject_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace visual_servoing

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'visual_servoing': ['/home/racecar/team-ws/src/racecar/visual_servoing/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::visual_servoing::CameraObject_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::visual_servoing::CameraObject_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::visual_servoing::CameraObject_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::visual_servoing::CameraObject_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::visual_servoing::CameraObject_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::visual_servoing::CameraObject_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::visual_servoing::CameraObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d478c17254577f2d7871f7b466c8761a";
  }

  static const char* value(const ::visual_servoing::CameraObject_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd478c17254577f2dULL;
  static const uint64_t static_value2 = 0x7871f7b466c8761aULL;
};

template<class ContainerAllocator>
struct DataType< ::visual_servoing::CameraObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "visual_servoing/CameraObject";
  }

  static const char* value(const ::visual_servoing::CameraObject_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::visual_servoing::CameraObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string label\n\
geometry_msgs/Point center  # in pixels, from center (haha, maybe not really)\n\
geometry_msgs/Vector3 size  # in pixels\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::visual_servoing::CameraObject_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::visual_servoing::CameraObject_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.label);
      stream.next(m.center);
      stream.next(m.size);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct CameraObject_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::visual_servoing::CameraObject_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::visual_servoing::CameraObject_<ContainerAllocator>& v)
  {
    s << indent << "label: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.label);
    s << indent << "center: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.center);
    s << indent << "size: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.size);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISUAL_SERVOING_MESSAGE_CAMERAOBJECT_H
